[package]
name = "nexus-emns"
version.workspace = true
edition.workspace = true

[features]
default = ["cuda"]
cuda = ["burn/cuda"]
rocm = ["burn/rocm"]
vulkan = ["burn/vulkan"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]

[dependencies]
cubecl = { workspace = true }
burn = { workspace = true, features = ["autodiff"] }
rayon = { workspace = true }
rand = { workspace = true }
