[package]
name = "nexus-memory"
version.workspace = true
edition.workspace = true

[features]
default = ["wgpu"]
cuda = ["burn/cuda"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { workspace = true }

memmap2 = { workspace = true }
zstd = { workspace = true }
serde = { workspace = true }
bincode = "1.3"
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"

